fix link
crystal-lang/shards pull request #500
Opened 2021-05-26 08:32 UTC by szabgab

2021-05-26 08:37 UTC, Sija requested changes

2021-05-26 08:37 UTC, Sija commented on README.md
> +Please see the [SPEC](https://github.com/ysbaddaden/shards/blob/master/docs/shard.yml.adoc)
```suggestion
Please see the [SPEC](https://github.com/crystal-lang/shards/blob/master/docs/shard.yml.adoc)
```

2021-05-26 08:56 UTC, straight-shoota approved these changes

2021-05-31 18:58 UTC, oprypin approved these changes

2021-05-31 19:08 UTC, jhass approved these changes

2021-05-31 19:35 UTC, merged