Add != operator for version resolve
crystal-lang/shards pull request #520
Opened 2021-08-14 02:03 UTC by syeopite

Closes #519

2021-08-18 17:58 UTC, beta-ziliani commented
The test is failing because of the formatter. Let me know @syeopite if you want me to take care of it, or if you can fix it.

2021-08-18 20:28 UTC, syeopite commented
Ah thanks! I couldn't figure out why CI was failing.

2021-08-18 20:40 UTC, beta-ziliani approved these changes
Once CI says so, I say this is ready to go. Thanks!

2021-08-18 21:48 UTC, Sija requested changes

2021-08-18 21:48 UTC, Sija commented on spec/unit/versions_spec.cr
> +        resolve(versions, "!= 0.1.0, != 0.2.0, != 0.10.0").should eq(["0.0.1", "0.1.1", "0.1.2"])
```suggestion
      resolve(versions, "!= 0.1.0").should eq(["0.0.1", "0.1.1", "0.1.2", "0.2.0", "0.10.0"])
      resolve(versions, "!= 0.1.0, != 0.2.0, != 0.10.0").should eq(["0.0.1", "0.1.1", "0.1.2"])
```

2021-08-23 15:57 UTC, syeopite commented on spec/unit/versions_spec.cr
> +      matches?("1.0.0", "> 0.1, < 1.0, != 1.0").should be_false
Yeah, I've noticed that a few days ago and fixed it in commit 30df126

2021-08-23 17:49 UTC, straight-shoota approved these changes

2021-09-20 12:45 UTC, merged